# Generated by Django 5.2.16 on 2026-08-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_bankaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
