# Generated by Django 5.2.16 on 2026-09-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='security_answer_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_question',
            field=models.CharField(blank=True, choices=[('first_pet', 'What was the name of your first pet?'), ('birth_city', 'In which city were you born?'), ('favorite_food', 'What is your favorite food?'), ('favorite_place', 'What is your favorite place to visit?'), ('school_name', 'What was the name of your first school?')], max_length=30, null=True),
        ),
    ]
