# Generated by Django 5.2.16 on 2026-08-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='icon',
            field=models.CharField(default='bi-bell', help_text='Bootstrap icon class, e.g. bi-gift', max_length=40),
        ),
    ]
