# Generated by Django 5.2.16 on 2026-08-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_alter_notification_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('LOAN', 'Loan'), ('ACCOUNT', 'Account'), ('PROMO', 'Promotional')], default='ACCOUNT', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='preset',
            field=models.CharField(choices=[('welcome', 'Welcome to SpendSmart Bank!'), ('approved', 'Account Approved'), ('freeze_warning', 'Account Freeze Warning'), ('loan_approved', 'Loan Application Approved'), ('loan_rejected', 'Loan Application Rejected'), ('loan_disbursed', 'Loan Disbursed'), ('loan_debited', 'EMI Deducted'), ('loan_due', 'EMI Due Soon'), ('salary_credited', 'Salary Credited'), ('festival_offer', 'Festival Offer'), ('rate_update', 'Interest Rate Update'), ('referral', 'Referral Programme'), ('custom', 'Custom Message')], default='custom', max_length=30),
        ),
    ]
