# Generated by Django 5.2.16 on 2026-08-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_notification_category_notification_is_important_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='category',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_important',
        ),
        migrations.AlterField(
            model_name='notification',
            name='preset',
            field=models.CharField(choices=[('welcome', 'Welcome to SpendSmart Bank!'), ('approved', 'Account Approved'), ('freeze_warning', 'Account Freeze Warning'), ('loan_approved', 'Loan Application Approved'), ('loan_rejected', 'Loan Application Rejected'), ('festival_offer', 'Festival Offer'), ('rate_update', 'Interest Rate Update'), ('referral', 'Referral Programme'), ('custom', 'Custom Message')], default='custom', max_length=30),
        ),
    ]
