# Generated by Django 6.0.7 on 2026-07-18 16:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=16, unique=True)),
                ('ifsc_code', models.CharField(default='VRTX0001234', max_length=11)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings Account'), ('CURRENT', 'Current Account')], default='SAVINGS', max_length=10)),
                ('upi_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('daily_transfer_limit', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('transaction_type', models.CharField(choices=[('SEND', 'Money Sent'), ('RECEIVE', 'Money Received'), ('SELF', 'Self Transfer')], default='SEND', max_length=10)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('note', models.CharField(blank=True, max_length=140)),
                ('failure_reason', models.CharField(blank=True, max_length=140)),
                ('sender_balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('receiver_balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='upi.bankaccount')),
                ('sender_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transactions', to='upi.bankaccount')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
