# Generated by Django 5.2.16 on 2026-08-08 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upi', '0002_bankaccount_blocked_balance_transaction_is_flagged_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='resolution_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recentcontact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
