# Generated by Django 5.2.16 on 2026-08-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upi', '0008_bankaccount_is_approved_requested_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
