# Generated by Django 5.2.16 on 2026-08-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upi', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
