# Generated by Django 5.2.16 on 2026-09-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanapplication_closed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='last_reminder_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
